### ISSUE TITLE
User / password ?!

### ISSUE THREAD

**Issue by Saesch** [sanjeshpathak/Mosquitto-Dashboard#1]
Hi,
your projects looks really cool, and i've try to start it. 
On the landing page, user / password were needed... where do i have to create this user / password?!
I'm complete new to mosquitto. 
Or it's possible to run the dashboard as public, means no user/password needed?!

Thx & Regards
Saesch

**Comment by sanjeshpathak** [comment]
Hi Saesch,

Thank you for the feedback. You can run Mosquitto broker in two modes -- anonymous mode, where you do not need username and password for connecting and client authentication mode. The article here explains how to configure Mosquitto for client authentication mode: http://www.steves-internet-guide.com/mqtt-username-password-example/

Sanjesh

**Comment by Saesch** [comment]
Food morning Sanjesh,
Thx for the response! I'll have a look and try it.
Regards feom Germany
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 26.03.19, 06:36, Sanjesh Pathak <notifications@github.com> schrieb:
Hi Saesch,
Thank you for the feedback. You can run Mosquitto broker in two modes -- anonymous mode, where you do not need username and password for connecting and client authentication mode. The article here explains how to configure Mosquitto for client authentication mode: http://www.steves-internet-guide.com/mqtt-username-password-example/
Sanjesh

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sanjeshpathak/Mosquitto-Dashboard","title":"sanjeshpathak/Mosquitto-Dashboard","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sanjeshpathak/Mosquitto-Dashboard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sanjeshpathak in #1: Hi Saesch,\r\n\r\nThank you for the feedback. You can run Mosquitto broker in two modes -- anonymous mode, where you do not need username and password for connecting and client authentication mode. The article here explains how to configure Mosquitto for client authentication mode: http://www.steves-internet-guide.com/mqtt-username-password-example/\r\n\r\nSanjesh"}],"action":{"name":"View Issue","url":"https://github.com/sanjeshpathak/Mosquitto-Dashboard/issues/1#issuecomment-476482270"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sanjeshpathak/Mosquitto-Dashboard/issues/1#issuecomment-476482270",
"url": "https://github.com/sanjeshpathak/Mosquitto-Dashboard/issues/1#issuecomment-476482270",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
